FROM python:3.8

WORKDIR /home/pymongoose
COPY . .

#python requirements for testing
RUN pip install --no-cache-dir -r requirements.txt

#pymongoose
RUN python -m pip install --upgrade pip
RUN pip install pytest pymongo pymongo[srv]

#Install packages
RUN python setup.py sdist
RUN pip install dist/pymongoose-*


CMD ["/bin/bash"]