name: Pymongoose Tests

on:
  pull_request:
    branches:
      - "*"
  
jobs:
  test:
    name: Pymongoose tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          python-version: 3.8
    
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest pymongo

      - name: Copy .pth file to directory
        run: |
          bash test.sh

      - name: Pymongoose unit testing
        env: 
          MONGO_URI: ${{ secrets.MONGO_URI }}
        run: |
          pytest tests/test.py

