name: Pymongoose Tests

on:
  pull_request:
    branches:
      - "*"
  
  jobs:
    tests:
      name: Pymongoose tests
      runs-on: ubuntu-latest
      steps:
        - name: Checkout
          uses: actions/checkout@v2
      
        - name: Build Docker Image
          run: docker build -t djcharles26/pymongoose:test -f Dockerfile.test .
        
        - name: Pymongoose unit Testing
          env: 
            MONGO_URI: ${{ secrets.MONGO_URI }}
          run: |
            sudo docker run -d --name test --rm  -e MONGO_URI=${MONGO_URI} djcharles26/pymongoose:test /bin/bash test.sh
            sleep 2
            sudo docker inspect test --format='{{.State.ExitCode}}' || { exit 1;}

